name: chinazo_scoreboard
description: "Aplicación para el scoreboard del juego Chinazo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

# pubspec.yaml (solo dependencias necesarias)
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  


# ¡SECCIÓN "flutter:" SIN ESPACIOS A LA IZQUIERDA!
flutter:
  uses-material-design: true  # <-- 2 espacios aquí
  assets:
    - assets/images/  # Incluye todo lo que esté en esta carpeta

